# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Peter Brunton, front end web development.
email: peterbrunton@peterbrunton.ie
description: > # this means to ignore newlines until "baseurl:"
  Portfolio site for Peter Brunton, front end web developer based out of Co Kerry Ireland and Faro Portugal.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: peterbruton
github_username:  peterbrunton

# Build settings
markdown: kramdown
