# Welcome to Jekyll!

# Website settings
title: "Peter Brunton, front end development"
description: "Pete's portfolio blog."
keywords: "Pete,Peter Brunton,blog,Jekyll,github,gh-pages"

baseurl: "/"
url: "peterbrunton.ie"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Peter Brunton'
  first_name: 'Peter'
  last_name: 'Brunton'
  email: 'brunton.peter@gmail.com'
  facebook_username: 'peterbrunton-webdevelopment'
  github_username: 'peterbrunton'
  head_img: 'static/img/landing/Peter.jpg'

# social link
jingyu:
  first_name: 'Peter'
  last_name: 'Brunton'
  description: 'FED'
  link: 'https://github.com/peterbrunton'
  email: 'brunton.peter@gmail.com'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'
  link: 'Link'

# my projects
project:
  jalpc:
    name: 'Peter'
    url: '/Jack614/jalpc_jekyll_theme'
    img: 'static/img/landing/jekyll.jpg'

# blog index
index:
  home: 'Home'
  shopify: 'Shopify'
  fed: 'front-end development'
  mac: 'Mac'  
  windows: 'windows'
  linux: 'Linux'
  life: 'Life'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: peter-brunton
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# blog img path
img_path: '/static/img/blog'

# Build settings
encoding: "utf-8"

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
